export const GET_PERSON_DETAIL_START = "GET_PERSON_DETAIL_START";
export const GET_PERSON_DETAIL_SUCCESS = "GET_PERSON_DETAIL_SUCCESS";
export const GET_PERSON_DETAIL_ERROR = "GET_PERSON_DETAIL_ERROR";

export const GET_PERSON_TV_CREDITS_START = "GET_PERSON_TV_CREDITS_START";
export const GET_PERSON_TV_CREDITS_SUCCESS = "GET_PERSON_TV_CREDITS_SUCCESS";
export const GET_PERSON_TV_CREDITS_ERROR = "GET_PERSON_TV_CREDITS_ERROR";

export const GET_PERSON_MOVIE_CREDITS_START = "GET_PERSON_MOVIE_CREDITS_START";
export const GET_PERSON_MOVIE_CREDITS_SUCCESS =
    "GET_PERSON_MOVIE_CREDITS_SUCCESS";
export const GET_PERSON_MOVIE_CREDITS_ERROR = "GET_PERSON_MOVIE_CREDITS_ERROR";
