export const GET_SEARCH_RESULTS_START = "GET_SEARCH_RESULTS_START";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_ERROR = "GET_SEARCH_RESULTS_ERROR";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
