export const GET_MOVIE_DETAIL_START = "GET_MOVIE_START";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_DETAIL_ERROR = "GET_MOVIE_ERROR";

export const GET_MOVIE_CAST_START = "GET_MOVIE_CAST_START";
export const GET_MOVIE_CAST_SUCCESS = "GET_MOVIE_CAST_SUCCESS";
export const GET_MOVIE_CAST_ERROR = "GET_MOVIE_CAST_ERROR";

export const GET_MOVIE_VIDEOS_START = "GET_MOVIE_VIDEOS_START";
export const GET_MOVIE_VIDEOS_SUCCESS = "GET_MOVIE_VIDEOS_SUCCESS";
export const GET_MOVIE_VIDEOS_ERROR = "GET_MOVIE_VIDEOS_ERROR";
